#!/usr/bin/env python3
"""
Import performers from scraped FreeOnes JSON into Local Stash.

Features:
- Uses input JSON generated by your scraper
- Saves progress after each performer (never lose data if crash)
- Auto-creates or updates performer in Stash
- Gender: ALWAYS FEMALE (as per your rule)
- Country: takes FIRST nationality, converts "America" → "United States of America"
- Measurements: Bra–Waist–Hip (Bust ignored)
- Fake Tits: from "Boobs" field
- Height (feet/in → cm), Weight (kg)
- Tattoos array handled as string
- Supports aliases
- Supports URLs
- Logs all operations
"""

import json
import requests
import time
import re
from pathlib import Path
from colorama import Fore, Style, init

init(autoreset=True)

# ---------------------------------------------------
# CONFIG PATHS
# ---------------------------------------------------
ROOT = Path(__file__).resolve().parents[1]
INPUT_JSON = ROOT / "data" / "pornstars-list-from-freeones.json"
LOG_FILE = ROOT / "stash" / "import_performers.log"


# Local stash config
STASH_URL = "http://localhost:9999/graphql"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJNci4gV2hpdGUiLCJzdWIiOiJBUElLZXkiLCJpYXQiOjE3NjM3NTg0NDN9.gaPhXh3QKIvJCW_JNygGZwlAOdzWFrRvgaQnbkWxEWU"

HEADERS = {"ApiKey": API_KEY, "Accept": "application/json"}

# ---------------------------------------------------
# LOGGING
# ---------------------------------------------------
def log(msg, level="info"):
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    tag = f"[{level.upper()}]"

    colors = {
        "info": Fore.CYAN + Style.BRIGHT,
        "success": Fore.GREEN + Style.BRIGHT,
        "warning": Fore.YELLOW + Style.BRIGHT,
        "error": Fore.RED + Style.BRIGHT
    }

    color = colors.get(level, Fore.WHITE)

    try:
        print(f"{color}{timestamp} {tag:<10}{Style.RESET_ALL} {msg}")
    except:
        print(f"{timestamp} {tag} {msg}")

    try:
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(f"{timestamp} {tag} {msg}\n")
    except:
        pass


# ---------------------------------------------------
# GRAPHQL HELPER
# ---------------------------------------------------
def gql(query, variables=None):
    r = requests.post(
        STASH_URL,
        json={"query": query, "variables": variables},
        headers=HEADERS
    )
    if r.status_code != 200:
        log(f"HTTP {r.status_code}: {r.text}", "error")
        return None
    try:
        return r.json()
    except:
        log(f"Invalid JSON: {r.text}", "error")
        return None


# ---------------------------------------------------
# GRAPHQL QUERIES
# ---------------------------------------------------
FIND_PERFORMER = """
query FindPerformer($name: String!) {
  findPerformers(performer_filter: {name: {value: $name, modifier: EQUALS}}) {
    count
    performers {
      id
      name
    }
  }
}
"""

CREATE_PERFORMER = """
mutation PerformerCreate($input: PerformerCreateInput!) {
  performerCreate(input: $input) {
    id
    name
  }
}
"""

UPDATE_PERFORMER = """
mutation PerformerUpdate($input: PerformerUpdateInput!) {
  performerUpdate(input: $input) {
    id
    name
  }
}
"""


# ---------------------------------------------------
# CONVERSION HELPERS
# ---------------------------------------------------
def convert_height_to_cm(height):
    """
    Convert height: "5'3"" → cm
    """
    m = re.match(r"(\d+)'(\d+)", height)
    if not m:
        return None
    ft = int(m.group(1))
    inch = int(m.group(2))
    total_in = ft * 12 + inch
    return round(total_in * 2.54)


def extract_urls(link_list):
    """ Extract URL list only """
    urls = []
    for item in link_list:
        if isinstance(item, dict) and "url" in item:
            urls.append(item["url"])
    return urls


def convert_rating100(r):
    """ Convert FreeOnes star rating → Stash rating100 """
    if not r:
        return None
    try:
        return int(float(r) * 20)
    except:
        return None


# ---------------------------------------------------
# BUILD PERFORMER PAYLOAD
# ---------------------------------------------------
def build_payload(name, data):
    payload = {
        "name": name,
        "gender": "FEMALE",     # RULE
        "details": data.get("Bio"),
        "ethnicity": data.get("Ethnicity"),
        "eye_color": data.get("Eye Color"),
        "hair_color": data.get("Hair Color"),
        "career_length": data.get("Career"),
        "alias_list": data.get("Aliases") or [],
        "urls": extract_urls(data.get("Links", [])),
        "rating100": convert_rating100(data.get("Rating"))
    }

    # -----------------------------------------
    # COUNTRY LOGIC
    # -----------------------------------------
    nat = data.get("Nationality")
    pob = data.get("Place of birth")

    def first_item(val):
        if isinstance(val, list):
            return val[0].strip() if val else None
        if isinstance(val, str):
            return val.strip()
        return None

    country = first_item(nat) or first_item(pob)

    # America fix
    if country:
        lc = country.lower()
        if lc in ["america", "american", "usa", "u.s.a", "united states"]:
            country = "United States of America"
        payload["country"] = country

    # -----------------------------------------
    # Height → cm
    # -----------------------------------------
    if data.get("Height"):
        cm = convert_height_to_cm(data["Height"])
        if cm:
            payload["height_cm"] = cm

    # -----------------------------------------
    # Weight (kg → int)
    # -----------------------------------------
    if data.get("Weight"):
        m = re.match(r"(\d+)", data["Weight"])
        if m:
            payload["weight"] = int(m.group(1))

    # -----------------------------------------
    # Tattoos
    # -----------------------------------------
    if data.get("Tattoo locations"):
        payload["tattoos"] = "; ".join(data["Tattoo locations"])

    # -----------------------------------------
    # Fake tits from Boobs
    # -----------------------------------------
    if data.get("Boobs"):
        payload["fake_tits"] = data["Boobs"]

    # -----------------------------------------
    # Measurements (Bra–Waist–Hip)
    # -----------------------------------------
    bra = data.get("Bra")
    waist = data.get("Waist")
    hip = data.get("Hip")

    def clean_num(v):
        return re.sub(r"[^0-9]", "", v) if v else None

    if bra and waist and hip:
        w = clean_num(waist)
        h = clean_num(hip)
        if w and h:
            payload["measurements"] = f"{bra}-{w}-{h}"

    # Clean nulls
    payload = {k: v for k, v in payload.items() if v}
    return payload


# ---------------------------------------------------
# IMPORT WORKFLOW
# ---------------------------------------------------
def find_local_performer(name):
    res = gql(FIND_PERFORMER, {"name": name})
    if not res or not res.get("data"):
        return None
    block = res["data"]["findPerformers"]
    if block["count"] == 0:
        return None
    return block["performers"][0]


def process_performer(name, data):
    log(f"→ Importing performer: {name}")

    existing = find_local_performer(name)
    payload = build_payload(name, data)

    if existing:
        # UPDATE
        payload["id"] = existing["id"]
        res = gql(UPDATE_PERFORMER, {"input": payload})
        if res and res.get("data") and not res.get("errors"):
            log(f"   ✅ Updated performer: {name}", "success")
            return True
        else:
            log(f"   ❌ Update failed: {res}", "error")
            return False

    else:
        # CREATE
        res = gql(CREATE_PERFORMER, {"input": payload})
        if res and res.get("data") and not res.get("errors"):
            log(f"   ✅ Created performer: {name}", "success")
            return True
        else:
            log(f"   ❌ Create failed: {res}", "error")
            return False


# ---------------------------------------------------
# MAIN
# ---------------------------------------------------
def main():
    if not INPUT_JSON.exists():
        log(f"Input JSON not found: {INPUT_JSON}", "error")
        return

    with open(INPUT_JSON, "r", encoding="utf-8") as f:
        performers = json.load(f)

    log(f"Loaded {len(performers)} performers")

    count = 0

    for name, data in performers.items():
        ok = process_performer(name, data)
        count += 1
        time.sleep(0.5)

    log(f"🎉 DONE — imported {count} performers.", "success")


if __name__ == "__main__":
    main()
